import Head from "next/head";
import { useState, useEffect } from "react";
import Link from "next/link";

import styles from "@/styles/Home.module.css";

export default function Home() {
  const imageSrc = [
    {
      id: 0,
      src: "https://openseauserdata.com/files/2213871af13c3deb5b33733a4e7006d7.svg",
    },
    {
      id: 1,
      src: "https://i.seadn.io/gcs/files/7b326549e4e70782f0f51f0b67c44278.png?auto=format&w=1000",
    },
    {
      id: 2,
      src: "https://i.seadn.io/gcs/files/6c85fd4fd844f5ca02d8bf97c8da3c67.png?auto=format&w=1000",
    },
  ];

  const [src, setSrc] = useState(
    "https://openseauserdata.com/files/2213871af13c3deb5b33733a4e7006d7.svg"
  );
  let initial = 1;
  useEffect(() => {
    const imageInterval = setInterval(() => {
      setSrc(imageSrc[initial].src);
      if (initial < imageSrc.length - 1) {
        initial++;
      } else {
        initial = 0;
      }
    }, 1000);
    return () => {
      clearInterval(imageInterval);
    };
  }, []);

  return (
    <div className="">
      <Head>
        <title>Vykt</title>
        <meta name="description" content="Generated by npx create-web3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-center items-center gap-10">
        <h1 className="text-white text-[3rem] mt-20">
          Generate profile picture for your{" "}
          <span className="text-green-400 underline">eth</span> address.
        </h1>
        <div className="h-3/12 w-2/12 overflow-hidden rounded-md">
          <img
            className="w-full h-full object-cover"
            src={src}
            alt=""
            draggable="false"
          />
        </div>
        <button className="px-5 hover:scale-110 transition-all duration-300 cursor-not-allowed ease-in py-2 bg-slate-800 rounded-lg text-[1.4rem] text-gray-400">
          coming soon
        </button>
        <p className="text-gray-500">
          Made with ♡ by{" "}
          <Link
            href="https://twitter.com/skeshav25"
            className="text-blue-500 underline relative cursor-pointer"
          >
            keshav
          </Link>{" "}
          and{" "}
          <Link
            href="https://twitter.com/miral182000"
            className="text-blue-500 underline cursor-pointer"
          >
            miral
          </Link>{" "}
          @{" "}
          <Link href="https://ethforall.devfolio.co/" className="text-white">
            ETHforAll
          </Link>
        </p>
      </main>
    </div>
  );
}
